---
- name: Uninstall Kaspersky Endpoint Security for Linux (KESL)
  block:
    - name: Check if KESL is installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Stop KESL service
      ansible.builtin.systemd:
        name: kesl
        state: stopped
      when: "'kesl' in ansible_facts.packages"
      ignore_errors: true

    - name: Remove KESL package
      ansible.builtin.apt:
        name: kesl
        state: absent
        purge: true
        autoremove: true
      when: "'kesl' in ansible_facts.packages"

    - name: Remove remaining KESL files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/kaspersky/kesl
        - /var/opt/kaspersky/kesl
        - /etc/systemd/system/kesl.service

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true