---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  listen: Restart SSH

- name: Restart SSH socket
  ansible.builtin.systemd:
    name: ssh.socket
    state: restarted
  become: true
  listen: Restart SSH

- name: Restart SSH service
  ansible.builtin.systemd:
    name: ssh.service
    state: restarted
  become: true
  listen: Restart SSH

- name: Restart Fail2Ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true
  become: true

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
    enabled: true
  become: true
