---
- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present
  become: true
  tags:
    - fail2ban

- name: Deploy fail2ban jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: "{{ fail2ban_jail_local_path }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
  become: true
  notify: Restart Fail2Ban
  tags:
    - fail2ban
