---
- name: Ensure that UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Policy Configuration
  block: 
    - name: Default incoming policy
      ufw:
        direction: incoming
        policy: "{{ ufw_default_input }}"

    - name: Default outgoing policy
      ufw:
        direction: outgoing
        policy: "{{ ufw_default_output }}"

    - name: Default routed policy
      ufw:
        direction: routed
        policy: "{{ ufw_default_forward }}"

- name: Configure firewall rules
  community.general.ufw:
    rule: "{{ item.action }}"
    direction: "{{ item.direction }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled