# Use password or ssh_key
ansible_user: vagrant
# ssh_key or password
ansible_connection_method: password
ansible_ssh_private_key_file: >-
  {{ '~/.ssh/id_ed25519' if ansible_connection_method == 'ssh_key' else omit }}
ansible_ssh_pass: >-
  {{ vault_ansible_ssh_pass if ansible_connection_method == 'password' else omit }}
