---

- name: Apt repository settings and credentials
  become: true
  when: configure_apt_repo | default(false) | bool
  block:

    - name: Copy nx apt public signing key
      ansible.builtin.copy:
        src: "nx-apt-public.key"
        dest: "/tmp/nx-apt-public.key"
        mode: "0640"

    - name: Check if default file exists
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/ubuntu.sources
      register: default_file

    - name: Rename file if it exists
      ansible.builtin.command: >
        mv /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.bak
      when: default_file.stat.exists

    - name: Check if nx_apt_keyring file exists
      ansible.builtin.stat:
        path: /usr/share/keyrings/nx-apt.gpg
      register: nx_apt_keyring

    - name: Dearmor NX apt public signing key
      become: true
      ansible.builtin.command: >
        gpg --dearmor -o /usr/share/keyrings/nx-apt.gpg /tmp/nx-apt-public.key
      when: not nx_apt_keyring.stat.exists

    - name: Apt repository settings
      become: true
      tags: apt_repo
      ansible.builtin.template:
        src: nxproxy.sources.j2
        dest: /etc/apt/sources.list.d/nx-proxy.sources
        owner: root
        group: root
        mode: '0640'

    - name: Apt repository credentials
      become: true
      tags: apt_repo
      ansible.builtin.template:
        src: nx-apt.conf.j2
        dest: /etc/apt/auth.conf.d/nx-apt.conf
        owner: root
        group: root
        mode: '0640'

- name: Set APT acquire timeout
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99timeout
    content: |
      Acquire::http::Timeout "60";
      Acquire::https::Timeout "60";
      Acquire::Retries "2";

- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: apt_update

- name: Upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
  become: true
  tags: apt_upgrade

- name: Install basic tools
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: true
    update_cache: true
  become: true
  tags: apt_basic_tools
