---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: apt_update

- name: Upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
  become: true
  tags: apt_upgrade

- name: Install basic tools
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: true
    update_cache: true
  become: true
  tags: apt_basic_tools
